# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        build_type:
          - Debug

    steps:
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt update -qq
          sudo apt install -y doxygen graphviz

      - name: Install ninja-build tool
        uses: aseprite/get-ninja@main

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure project
        run: >
          cmake -S . -B ./build -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DKDSPDSETUP_BUILD_TESTS=ON
          -DKDSPDSETUP_BUILD_EXAMPLES=ON
          -DKDSPDSETUP_BUILD_DOCS=${{ runner.os == 'Linux' }}

      - name: Build Project
        run: cmake --build ./build

      - name: Run tests
        run: ctest --test-dir ./build -C ${{ matrix.build_type }} --output-on-failure

      - name: Read tests log when it fails
        uses: andstor/file-reader-action@v1
        if: ${{ failure() }}
        with:
          path: "./build/Testing/Temporary/LastTest.log"
